export type DummyUser = { email: string; role: "customer" | "admin" };
export type CustomerProfile = { name: string; whatsapp: string; address: string };
export const ADMIN_EMAIL = "admin@gmail.com";
export const ADMIN_PASSWORD = "admin123";
const SESSION_KEY = "rumah-rona-session";
const USERS_KEY = "rumah-rona-users";

export function getDummySession(): DummyUser | null { if (typeof window === "undefined") return null; try { const value = window.localStorage.getItem(SESSION_KEY); if (!value) return null; const user = JSON.parse(value) as DummyUser; return user?.email && (user.role === "admin" || user.role === "customer") ? user : null; } catch { window.localStorage.removeItem(SESSION_KEY); return null; } }
export function signOutDummy() { window.localStorage.removeItem(SESSION_KEY); window.dispatchEvent(new Event("rumah-rona-auth")); window.location.href = "/"; }
function getLocalUsers(): Record<string, { password: string; profile: CustomerProfile }> { try { const raw = JSON.parse(window.localStorage.getItem(USERS_KEY) ?? "{}"); return Object.fromEntries(Object.entries(raw).map(([email, value]) => typeof value === "string" ? [email, { password: value, profile: { name: email.split("@")[0], whatsapp: "", address: "" } }] : [email, value])) as Record<string, { password: string; profile: CustomerProfile }>; } catch { window.localStorage.removeItem(USERS_KEY); return {}; } }
export function getDummyProfile(email?: string): CustomerProfile { if (!email || typeof window === "undefined") return { name: "", whatsapp: "", address: "" }; return getLocalUsers()[email.trim().toLowerCase()]?.profile ?? { name: email.split("@")[0], whatsapp: "", address: "" }; }
export function signInDummy(email: string, password: string): DummyUser | null { const key = email.trim().toLowerCase(); if (key === ADMIN_EMAIL && password === ADMIN_PASSWORD) { const user = { email: ADMIN_EMAIL, role: "admin" as const }; window.localStorage.setItem(SESSION_KEY, JSON.stringify(user)); return user; } const users = getLocalUsers(); if (users[key]?.password !== password) return null; const user = { email: key, role: "customer" as const }; window.localStorage.setItem(SESSION_KEY, JSON.stringify(user)); return user; }
export function signUpDummy(email: string, password: string, profile?: CustomerProfile): DummyUser | null { const key = email.trim().toLowerCase(); if (!key || !key.endsWith("@gmail.com") || key === ADMIN_EMAIL || password.length < 6) return null; const users = getLocalUsers(); users[key] = { password, profile: profile ?? users[key]?.profile ?? { name: key.split("@")[0], whatsapp: "", address: "" } }; window.localStorage.setItem(USERS_KEY, JSON.stringify(users)); const user = { email: key, role: "customer" as const }; window.localStorage.setItem(SESSION_KEY, JSON.stringify(user)); return user; }
export function saveDummyProfile(email: string, profile: CustomerProfile) { if (typeof window === "undefined") return; const users = getLocalUsers(); if (!users[email]) return; users[email].profile = profile; window.localStorage.setItem(USERS_KEY, JSON.stringify(users)); }
