"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { formatPrice, Product, products } from "../components/types";
import AuthModal from "../components/AuthModal";
import { DummyUser, getDummySession, signOutDummy } from "../lib/dummyAuth";
import { getLocalOrders } from "../lib/localOrders";

type SaleItem = { product_name: string; size: string; quantity: number; price: number };
type Sale = { id: string; order_number: string; customer_name: string; whatsapp: string; address: string; payment_method: string; total: number; created_at: string; items: SaleItem[] };
type RemoteProduct = { id: string | number; name: string; price: number; category: string; stock: number; description: string };
type ProductForm = { id?: string | number; name: string; price: string; category: string; stock: string; description: string };
const emptyForm: ProductForm = { name: "", price: "", category: "Atasan", stock: "10", description: "" };

export default function AdminPage() {
  const [user, setUser] = useState<DummyUser | null>(null);
  const [sales, setSales] = useState<Sale[]>([]);
  const [remoteProducts, setRemoteProducts] = useState<RemoteProduct[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [authError, setAuthError] = useState("");
  const [selected, setSelected] = useState<Sale | null>(null);
  const [activeTab, setActiveTab] = useState("Dashboard");
  const [form, setForm] = useState<ProductForm>(emptyForm);

  useEffect(() => { const sync = async () => { const localUser = getDummySession(); if (localUser) { setUser(localUser); return; } const session = await supabase?.auth.getSession(); const email = session?.data.session?.user.email; if (email) setUser({ email, role: email.toLowerCase() === "admin@gmail.com" ? "admin" : "customer" }); }; sync(); const listener = supabase?.auth.onAuthStateChange((_event, session) => { const email = session?.user.email; if (email) setUser({ email, role: email.toLowerCase() === "admin@gmail.com" ? "admin" : "customer" }); }); return () => listener?.data.subscription.unsubscribe(); }, []);

  const loadData = async () => { if (!supabase) { setSales(getLocalOrders()); setLoading(false); return; } const [{ data: productData, error: productError }, { data: orderData, error: orderError }] = await Promise.all([supabase.from("products").select("id, name, price, category, stock, description").order("name"), supabase.from("orders").select("id, order_number, customer_name, whatsapp, address, payment_method, total, created_at").order("created_at", { ascending: false })]); if (productError) setError(`Produk Supabase tidak terbaca: ${productError.message}`); if (productData) setRemoteProducts(productData.map((item) => ({ id: item.id, name: item.name, price: Number(item.price), category: item.category || "Atasan", stock: Number(item.stock ?? 0), description: item.description || "" }))); if (orderError) { setSales(getLocalOrders()); setError((current) => current || "Pesanan database belum dapat diakses."); setLoading(false); return; } const ids = (orderData ?? []).map((item) => item.id); const { data: itemData, error: itemError } = ids.length ? await supabase.from("order_items").select("order_id, product_name, size, quantity, price").in("order_id", ids) : { data: [], error: null }; if (itemError) setError(itemError.message); const remoteSales = (orderData ?? []).map((order) => ({ ...order, items: (itemData ?? []).filter((item) => item.order_id === order.id) } as Sale)); setSales([...remoteSales, ...getLocalOrders()]); setLoading(false); };
  useEffect(() => { if (user?.role === "admin") loadData(); }, [user]);

  const productsForAdmin = useMemo(() => remoteProducts.length ? remoteProducts : products.map((product) => ({ id: product.id, name: product.name, price: product.price, category: product.category, stock: product.stock ?? 10, description: product.description })), [remoteProducts]);
  const revenue = sales.reduce((sum, sale) => sum + Number(sale.total), 0); const units = sales.flatMap((sale) => sale.items).reduce((sum, item) => sum + item.quantity, 0); const customers = new Set(sales.map((sale) => sale.customer_name)).size;
  const soldFor = (name: string) => sales.flatMap((sale) => sale.items).filter((item) => item.product_name.trim().toLowerCase() === name.trim().toLowerCase()).reduce((sum, item) => sum + item.quantity, 0);

  const editProduct = (product: RemoteProduct) => { setActiveTab("Produk"); setForm({ id: product.id, name: product.name, price: String(product.price), category: product.category, stock: String(product.stock), description: product.description }); };
  const saveProduct = async (event: FormEvent) => { event.preventDefault(); if (!supabase || !form.name.trim() || !form.price || !form.stock) { setError("Lengkapi nama, harga, dan stok produk."); return; } setSaving(true); setError(""); const payload = { name: form.name.trim(), price: Number(form.price), category: form.category, stock: Math.max(0, Number(form.stock)), description: form.description.trim() }; const result = form.id === undefined ? await supabase.from("products").insert(payload).select("id, name, price, category, stock, description").single() : await supabase.from("products").update(payload).eq("id", form.id).select("id, name, price, category, stock, description").single(); if (result.error && /description|column/i.test(result.error.message)) { const fallbackPayload = { name: payload.name, price: payload.price, category: payload.category, stock: payload.stock }; const fallback = form.id === undefined ? await supabase.from("products").insert(fallbackPayload).select("id, name, price, category, stock").single() : await supabase.from("products").update(fallbackPayload).eq("id", form.id).select("id, name, price, category, stock").single(); if (fallback.error) setError(fallback.error.message); else { setRemoteProducts((current) => form.id === undefined ? [...current, { ...fallback.data, description: payload.description }] : current.map((item) => item.id === form.id ? { ...item, ...fallback.data, description: payload.description } : item)); setForm(emptyForm); } } else if (result.error) setError(result.error.message); else { setRemoteProducts((current) => form.id === undefined ? [...current, result.data as RemoteProduct] : current.map((item) => item.id === form.id ? result.data as RemoteProduct : item)); setForm(emptyForm); } setSaving(false); };
  const deleteProduct = async (id: string | number) => { if (!supabase || !window.confirm("Hapus produk ini?")) return; const { error: deleteError } = await supabase.from("products").delete().eq("id", id); if (deleteError) setError(`Produk gagal dihapus: ${deleteError.message}`); else setRemoteProducts((current) => current.filter((item) => item.id !== id)); };
  const stockChange = async (product: RemoteProduct, amount: number) => { if (!supabase) return; const next = Math.max(0, product.stock + amount); const { error: updateError } = await supabase.from("products").update({ stock: next }).eq("id", product.id); if (updateError) setError(updateError.message); else setRemoteProducts((current) => current.map((item) => item.id === product.id ? { ...item, stock: next } : item)); };

  const productManager = <section className="admin-panel product-manager"><div className="panel-heading"><div><p className="eyebrow">KELOLA KATALOG</p><h2>{form.id === undefined ? "Tambah Produk" : "Edit Produk"}</h2></div>{form.id !== undefined && <button className="panel-link" type="button" onClick={() => setForm(emptyForm)}>Batal edit</button>}</div><form className="admin-product-form" onSubmit={saveProduct}><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Nama produk" required/><input type="number" min="0" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} placeholder="Harga" required/><select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option>Atasan</option><option>Bawahan</option><option>Outer</option><option>Dress</option></select><input type="number" min="0" value={form.stock} onChange={(event) => setForm({ ...form, stock: event.target.value })} placeholder="Stok" required/><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Deskripsi produk" rows={3}/><button className="button dark" type="submit" disabled={saving}>{saving ? "MENYIMPAN..." : form.id === undefined ? "TAMBAH PRODUK →" : "SIMPAN PERUBAHAN →"}</button></form></section>;
  const productTable = <section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">DATA PRODUK</p><h2>Produk Tersimpan</h2></div></div><div className="admin-product-list">{productsForAdmin.map((product) => <div className="admin-product-row" key={product.id}><div><b>{product.name}</b><small>{product.category} · {formatPrice(product.price)} · terjual {soldFor(product.name)} pcs</small></div><div className="admin-product-actions"><button type="button" onClick={() => stockChange(product, -1)} disabled={product.stock <= 0}>−</button><strong>{product.stock} pcs</strong><button type="button" onClick={() => stockChange(product, 1)}>+</button><button type="button" onClick={() => editProduct(product)}>EDIT</button><button type="button" className="danger" onClick={() => deleteProduct(product.id)}>HAPUS</button></div></div>)}</div></section>;
  const ordersTable = <section className="admin-panel recent-orders"><div className="panel-heading"><div><p className="eyebrow">DATA PESANAN</p><h2>Pesanan</h2></div></div>{loading ? <p className="report-muted">Memuat data...</p> : sales.length === 0 ? <p className="report-muted">Belum ada transaksi.</p> : <div className="recent-order-list">{sales.map((sale) => <button className="recent-order" key={sale.id} onClick={() => setSelected(sale)}><span className="order-mark">▤</span><span><b>{sale.order_number}</b><small>{sale.customer_name} · {new Date(sale.created_at).toLocaleDateString("id-ID")}</small></span><strong>{formatPrice(Number(sale.total))}</strong><i>→</i></button>)}</div>}</section>;
  const dashboard = <><section className="admin-stat-grid"><div className="admin-stat-card"><b>{productsForAdmin.length}</b><span>Produk terdaftar</span></div><div className="admin-stat-card"><b>{sales.length}</b><span>Total pesanan</span><small>{units} unit terjual</small></div><div className="admin-stat-card"><b>{customers}</b><span>Akun pembeli</span></div><div className="admin-stat-card"><b>{formatPrice(revenue)}</b><span>Pendapatan</span></div></section>{productTable}{ordersTable}</>;
  const categories = [...new Set(productsForAdmin.map((product) => product.category))].map((category) => ({ category, count: productsForAdmin.filter((product) => product.category === category).length }));
  const content = activeTab === "Dashboard" ? dashboard : activeTab === "Produk" ? <>{productManager}{productTable}</> : activeTab === "Kategori" ? <section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">KATALOG</p><h2>Kategori Produk</h2></div></div>{categories.map((item) => <div className="low-stock-row" key={item.category}><span>{item.category}<small>Produk dalam kategori</small></span><b>{item.count} produk</b></div>)}</section> : activeTab === "Pesanan" ? ordersTable : <><section className="admin-stat-grid"><div className="admin-stat-card"><b>{formatPrice(revenue)}</b><span>Total pendapatan</span></div><div className="admin-stat-card"><b>{sales.length}</b><span>Pesanan masuk</span></div><div className="admin-stat-card"><b>{units}</b><span>Unit terjual</span></div></section>{ordersTable}</>;

  if (!user || user.role !== "admin") return <main className="admin-page"><div className="admin-head"><div><p className="eyebrow">RUMAH RONA · ADMIN</p><h1>Login admin</h1><p>Masuk untuk mengelola toko dan melihat laporan.</p>{authError && <p className="auth-error">{authError}</p>}</div><a className="back-link" href="/">← Kembali ke toko</a></div><AuthModal onClose={() => window.location.href = "/"} onAuthenticated={(authenticatedUser) => authenticatedUser.role === "admin" ? (setUser(authenticatedUser), setAuthError("")) : setAuthError("Akun ini bukan akun admin.")} /></main>;
  return <main className="admin-page admin-dashboard"><header className="admin-topbar"><div className="admin-brand"><span>✦</span><div><b>RUMAH RONA</b><small>Admin workspace</small></div></div><div className="admin-user"><span className="admin-avatar">A</span><span>{user.email}</span><button onClick={() => { signOutDummy(); supabase?.auth.signOut(); }}>Keluar</button></div></header><nav className="admin-nav">{["Dashboard", "Produk", "Kategori", "Pesanan", "Laporan Penjualan"].map((tab) => <button type="button" key={tab} className={activeTab === tab ? "active" : ""} onClick={() => setActiveTab(tab)}><span>{tab}</span></button>)}</nav><section className="admin-welcome"><div><p className="eyebrow">OVERVIEW · RUMAH RONA</p><h1>{activeTab}</h1><p>Kelola katalog, stok, pesanan, dan laporan toko.</p></div><a className="admin-store-link" href="/" onClick={() => { signOutDummy(); supabase?.auth.signOut(); }}>Lihat toko ↗</a></section>{error && <p className="auth-error admin-notice">{error}</p>}{content}{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><article className="receipt" onClick={(event) => event.stopPropagation()}><button className="close no-print" onClick={() => setSelected(null)}>×</button><div className="receipt-content"><p className="eyebrow">RUMAH RONA</p><h2>Struk penjualan</h2><p className="receipt-number">{selected.order_number} · {new Date(selected.created_at).toLocaleString("id-ID")}</p><div className="receipt-customer"><b>{selected.customer_name}</b><span>{selected.whatsapp}</span><span>{selected.address}</span></div>{selected.items.map((item, index) => <div className="receipt-item" key={`${item.product_name}-${item.size}-${index}`}><span>{item.product_name}<small>{item.size} · × {item.quantity}</small></span><b>{formatPrice(item.price * item.quantity)}</b></div>)}<div className="receipt-total"><span>Total</span><b>{formatPrice(Number(selected.total))}</b></div><p className="receipt-payment">Pembayaran: {selected.payment_method}</p><button className="button dark no-print" onClick={() => window.print()}>CETAK STRUK →</button></div></article></div>}</main>;
}
