"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { formatPrice, products } from "../components/types";
type Sale = { id: string; order_number: string; customer_name: string; whatsapp: string; address: string; payment_method: string; total: number; created_at: string; items: { product_name: string; size: string; quantity: number; price: number }[] };
const INITIAL_STOCK = 10;
export default function AdminPage() {
  const [sales, setSales] = useState<Sale[]>([]); const [selected, setSelected] = useState<Sale | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { (async () => { const { data, error: orderError } = await supabase.from("orders").select("id, order_number, customer_name, whatsapp, address, payment_method, total, created_at").order("created_at", { ascending: false }); if (orderError) { setError(orderError.message); setLoading(false); return; } const ids = (data ?? []).map((item) => item.id); const { data: itemData, error: itemError } = ids.length ? await supabase.from("order_items").select("order_id, product_name, size, quantity, price").in("order_id", ids) : { data: [], error: null }; if (itemError) setError(itemError.message); setSales((data ?? []).map((order) => ({ ...order, items: (itemData ?? []).filter((item) => item.order_id === order.id) } as Sale))); setLoading(false); })(); }, []);
  const stock = useMemo(() => products.map((product) => { const sold = sales.flatMap((sale) => sale.items).filter((item) => item.product_name === product.name).reduce((sum, item) => sum + item.quantity, 0); return { ...product, sold, remaining: Math.max(0, INITIAL_STOCK - sold) }; }), [sales]);
  const revenue = sales.reduce((sum, sale) => sum + Number(sale.total), 0); const units = sales.flatMap((sale) => sale.items).reduce((sum, item) => sum + item.quantity, 0);
  return <main className="admin-page"><div className="admin-head"><div><p className="eyebrow">RUMAH RONA · ADMIN</p><h1>Laporan penjualan</h1><p>Ringkasan pesanan, struk, dan ketersediaan stok.</p></div><a className="back-link" href="/">← Kembali ke toko</a></div><div className="report-stats"><div><span>Total penjualan</span><b>{formatPrice(revenue)}</b></div><div><span>Pesanan</span><b>{sales.length}</b></div><div><span>Unit terjual</span><b>{units}</b></div></div><section className="stock-report"><div className="report-title"><div><p className="eyebrow">INVENTARIS</p><h2>Jumlah stok</h2></div><small>Stok awal: {INITIAL_STOCK} / produk</small></div><div className="stock-grid">{stock.map((item) => <div className="stock-row" key={item.id}><span>{item.name}<small>{item.category}</small></span><b className={item.remaining < 3 ? "low-stock" : ""}>{item.remaining} <small>tersisa</small></b></div>)}</div></section><section className="sales-report"><div className="report-title"><div><p className="eyebrow">TRANSAKSI</p><h2>Pesanan terbaru</h2></div></div>{loading ? <p className="report-muted">Memuat laporan...</p> : error ? <p className="auth-error">Gagal memuat laporan: {error}</p> : sales.length === 0 ? <p className="report-muted">Belum ada transaksi.</p> : <div className="sales-table"><div className="sales-table-head"><span>Nomor pesanan</span><span>Pelanggan</span><span>Total</span><span></span></div>{sales.map((sale) => <div className="sales-row" key={sale.id}><span><b>{sale.order_number}</b><small>{new Date(sale.created_at).toLocaleDateString("id-ID")}</small></span><span>{sale.customer_name}</span><b>{formatPrice(Number(sale.total))}</b><button onClick={() => setSelected(sale)}>LIHAT STRUK →</button></div>)}</div>}</section>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><article className="receipt" onClick={(event) => event.stopPropagation()}><button className="close no-print" onClick={() => setSelected(null)}>×</button><div className="receipt-content"><p className="eyebrow">RUMAH RONA</p><h2>Struk penjualan</h2><p className="receipt-number">{selected.order_number} · {new Date(selected.created_at).toLocaleString("id-ID")}</p><div className="receipt-customer"><b>{selected.customer_name}</b><span>{selected.whatsapp}</span><span>{selected.address}</span></div>{selected.items.map((item, index) => <div className="receipt-item" key={`${item.product_name}-${item.size}-${index}`}><span>{item.product_name}<small>{item.size} · × {item.quantity}</small></span><b>{formatPrice(item.price * item.quantity)}</b></div>)}<div className="receipt-total"><span>Total</span><b>{formatPrice(Number(selected.total))}</b></div><p className="receipt-payment">Pembayaran: {selected.payment_method}</p><button className="button dark no-print" onClick={() => window.print()}>CETAK STRUK →</button></div></article></div>}</main>;
}
