"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { formatPrice, Product, products } from "../components/types";
import AuthModal from "../components/AuthModal";
import { DummyUser, getDummySession, signOutDummy } from "../lib/dummyAuth";
import { getLocalOrders, getOrderStatus, orderStatuses, OrderStatus, saveOrderStatus } from "../lib/localOrders";
import { getProductCache, saveProductCache } from "../lib/productCache";
import { getCategoryCache, saveCategoryCache } from "../lib/categoryCache";

type SaleItem = { product_name: string; size: string; quantity: number; price: number };
type Sale = { id: string; order_number: string; customer_name: string; whatsapp: string; address: string; payment_method: string; total: number; created_at: string; status?: OrderStatus; items: SaleItem[] };
type RemoteProduct = { id: string | number; name: string; price: number; category: string; stock: number; description: string };
type ProductForm = { id?: string | number; name: string; price: string; category: string; stock: string; description: string };
const emptyForm: ProductForm = { name: "", price: "", category: "Atasan", stock: "10", description: "" };
const sameProductId = (first: string | number | undefined, second: string | number | undefined) => first !== undefined && second !== undefined && String(first) === String(second);

export default function AdminPage() {
  const [user, setUser] = useState<DummyUser | null>(null);
  const [sales, setSales] = useState<Sale[]>([]);
  const [remoteProducts, setRemoteProducts] = useState<RemoteProduct[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [authError, setAuthError] = useState("");
  const [selected, setSelected] = useState<Sale | null>(null);
  const [activeTab, setActiveTab] = useState("Dashboard");
  const [form, setForm] = useState<ProductForm>(emptyForm);
  const [editingId, setEditingId] = useState<string | number | null>(null);
  const [newCategory, setNewCategory] = useState("");
  const [editingCategory, setEditingCategory] = useState<string | null>(null);
  const [savedCategories, setSavedCategories] = useState<string[]>([]);
  const [reportPeriod, setReportPeriod] = useState("semua");
  const [reportFrom, setReportFrom] = useState("");
  const [reportTo, setReportTo] = useState("");
  const [reportCategory, setReportCategory] = useState("Semua kategori");
  const [printingReport, setPrintingReport] = useState(false);
  const [chartPeriod, setChartPeriod] = useState("7-hari");
  const [chartFrom, setChartFrom] = useState("");
  const [chartTo, setChartTo] = useState("");
  const adminTabs = ["Dashboard", "Produk", "Kategori", "Pesanan", "Laporan Penjualan"];

  useEffect(() => { const sync = async () => { const localUser = getDummySession(); if (localUser) { setUser(localUser); return; } const session = await supabase?.auth.getSession(); const email = session?.data.session?.user.email; if (email) setUser({ email, role: email.toLowerCase() === "admin@gmail.com" ? "admin" : "customer" }); }; sync(); const listener = supabase?.auth.onAuthStateChange((_event, session) => { const email = session?.user.email; if (email) setUser({ email, role: email.toLowerCase() === "admin@gmail.com" ? "admin" : "customer" }); }); return () => listener?.data.subscription.unsubscribe(); }, []);

  const loadData = async () => { if (!supabase) { setSales(getLocalOrders().map((sale) => ({ ...sale, status: getOrderStatus(sale.order_number, sale.status) }))); setLoading(false); return; } const [{ data: productData, error: productError }, { data: orderData, error: orderError }] = await Promise.all([supabase.from("products").select("id, name, price, category, stock").order("name"), supabase.from("orders").select("id, order_number, customer_name, whatsapp, address, payment_method, total, created_at, status").order("created_at", { ascending: false })]); if (productError) setError(`Produk Supabase tidak terbaca: ${productError.message}`); if (productData) { const cached = getProductCache(); const merged = productData.map((item) => cached.find((saved) => String(saved.id) === String(item.id)) ?? item); cached.forEach((saved) => { if (!merged.some((item) => String(item.id) === String(saved.id))) merged.push(saved); }); setRemoteProducts(merged.map((item) => ({ id: item.id, name: item.name, price: Number(item.price), category: item.category || "Atasan", stock: Number(item.stock ?? 0), description: (item as { description?: string }).description || "" }))); } if (orderError) { setSales(getLocalOrders().map((sale) => ({ ...sale, status: getOrderStatus(sale.order_number, sale.status) }))); setError((current) => current || "Pesanan database belum dapat diakses."); setLoading(false); return; } const ids = (orderData ?? []).map((item) => item.id); const { data: itemData, error: itemError } = ids.length ? await supabase.from("order_items").select("order_id, product_name, size, quantity, price").in("order_id", ids) : { data: [], error: null }; if (itemError) setError(itemError.message); const remoteSales = (orderData ?? []).map((order) => ({ ...order, status: order.status ?? getOrderStatus(order.order_number), items: (itemData ?? []).filter((item) => item.order_id === order.id) } as Sale)); setSales([...remoteSales, ...getLocalOrders().map((sale) => ({ ...sale, status: getOrderStatus(sale.order_number, sale.status) }))]); setLoading(false); };
  useEffect(() => { if (user?.role === "admin") loadData(); }, [user]);
  useEffect(() => { setSavedCategories(getCategoryCache()); }, []);
  useEffect(() => { const savedTab = window.sessionStorage.getItem("rumah-rona-admin-tab"); if (savedTab && adminTabs.includes(savedTab)) setActiveTab(savedTab); }, []);

  const productsForAdmin = useMemo(() => remoteProducts.length ? remoteProducts : products.map((product) => ({ id: product.id, name: product.name, price: product.price, category: product.category, stock: product.stock ?? 10, description: product.description })), [remoteProducts]);
  const revenue = sales.reduce((sum, sale) => sum + Number(sale.total), 0); const units = sales.flatMap((sale) => sale.items).reduce((sum, item) => sum + item.quantity, 0); const customers = new Set(sales.map((sale) => sale.customer_name)).size; const categoryNames = [...new Set([...savedCategories, ...remoteProducts.map((product) => product.category), ...products.map((product) => product.category)])].filter(Boolean).sort();
  const soldFor = (name: string) => sales.flatMap((sale) => sale.items).filter((item) => item.product_name.trim().toLowerCase() === name.trim().toLowerCase()).reduce((sum, item) => sum + item.quantity, 0);
  const salesTrend = useMemo(() => {
    const today = new Date();
    const end = chartTo ? new Date(`${chartTo}T23:59:59.999`) : new Date(today.getFullYear(), today.getMonth(), today.getDate(), 23, 59, 59, 999);
    let start: Date;
    if (chartFrom) start = new Date(`${chartFrom}T00:00:00`);
    else if (chartPeriod === "30-hari") start = new Date(end.getFullYear(), end.getMonth(), end.getDate() - 29);
    else if (chartPeriod === "3-bulan") start = new Date(end.getFullYear(), end.getMonth(), end.getDate() - 89);
    else if (chartPeriod === "tahun-ini") start = new Date(end.getFullYear(), 0, 1);
    else if (chartPeriod === "semua") start = sales.length ? new Date(Math.min(...sales.map((sale) => new Date(sale.created_at).getTime()))) : new Date(end.getFullYear(), end.getMonth(), end.getDate() - 6);
    else start = new Date(end.getFullYear(), end.getMonth(), end.getDate() - 6);
    const range = Math.max(end.getTime() - start.getTime(), 24 * 60 * 60 * 1000);
    const days = Array.from({ length: 7 }, (_, index) => {
      const bucketStart = new Date(start.getTime() + (range * index) / 7);
      const bucketEnd = new Date(start.getTime() + (range * (index + 1)) / 7);
      const bucketSales = sales.filter((sale) => { const createdAt = new Date(sale.created_at); return createdAt >= bucketStart && (index === 6 ? createdAt <= end : createdAt < bucketEnd); });
      return { label: bucketStart.toLocaleDateString("id-ID", { day: "2-digit", month: "short" }), date: index + 1, revenue: bucketSales.reduce((sum, sale) => sum + Number(sale.total), 0) };
    });
    const maxRevenue = Math.max(...days.map((day) => day.revenue), 1);
    const points = days.map((day, index) => ({ ...day, x: 42 + index * 106, y: 214 - (day.revenue / maxRevenue) * 164 }));
    return { days, maxRevenue, points, line: points.map((point) => `${point.x},${point.y}`).join(" ") };
  }, [sales, chartPeriod, chartFrom, chartTo]);
  const reportSales = useMemo(() => {
    const now = new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    let periodFrom: Date | null = null;
    let periodTo: Date | null = null;
    if (reportPeriod === "hari-ini") periodFrom = periodTo = today;
    if (reportPeriod === "7-hari") { periodFrom = new Date(today); periodFrom.setDate(today.getDate() - 6); periodTo = today; }
    if (reportPeriod === "bulan-ini") { periodFrom = new Date(today.getFullYear(), today.getMonth(), 1); periodTo = today; }
    if (reportPeriod === "tahun-ini") { periodFrom = new Date(today.getFullYear(), 0, 1); periodTo = today; }
    const from = reportFrom ? new Date(`${reportFrom}T00:00:00`) : periodFrom;
    const to = reportTo ? new Date(`${reportTo}T23:59:59.999`) : periodTo;
    const categoryOf = (item: SaleItem) => productsForAdmin.find((product) => product.name.trim().toLowerCase() === item.product_name.trim().toLowerCase())?.category;
    return sales.filter((sale) => {
      const createdAt = new Date(sale.created_at);
      const dateMatches = (!from || createdAt >= from) && (!to || createdAt <= to);
      const itemsMatch = reportCategory === "Semua kategori" || sale.items.some((item) => categoryOf(item) === reportCategory);
      return dateMatches && itemsMatch;
    });
  }, [sales, productsForAdmin, reportPeriod, reportFrom, reportTo, reportCategory]);
  const reportItems = reportSales.flatMap((sale) => sale.items.filter((item) => reportCategory === "Semua kategori" || productsForAdmin.find((product) => product.name.trim().toLowerCase() === item.product_name.trim().toLowerCase())?.category === reportCategory));
  const reportRevenue = reportCategory === "Semua kategori" ? reportSales.reduce((sum, sale) => sum + Number(sale.total), 0) : reportItems.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const reportUnits = reportItems.reduce((sum, item) => sum + item.quantity, 0);
  const reportCustomers = new Set(reportSales.map((sale) => sale.customer_name)).size;
  const reportDescription = [reportFrom || reportTo ? `${reportFrom || "awal"} — ${reportTo || "sekarang"}` : reportPeriod === "semua" ? "Semua periode" : reportPeriod.replaceAll("-", " "), reportCategory].join(" · ");
  const printReport = () => { setPrintingReport(true); window.setTimeout(() => { window.print(); window.setTimeout(() => setPrintingReport(false), 500); }, 50); };

  const editProduct = (product: RemoteProduct) => { setActiveTab("Produk"); setError(""); setEditingId(product.id); setForm({ id: product.id, name: product.name, price: String(product.price), category: product.category, stock: String(product.stock), description: product.description }); };
  const saveProduct = async (event: FormEvent) => { event.preventDefault(); if (!supabase || !form.name.trim() || !form.price || !form.stock) { setError("Lengkapi nama, harga, dan stok produk."); return; } const client = supabase; setSaving(true); setError(""); const isEdit = editingId !== null; const payload = { name: form.name.trim(), price: Number(form.price), category: form.category, stock: Math.max(0, Number(form.stock)), description: form.description.trim() }; const run = (data: { name: string; price: number; category: string; stock: number; description?: string }) => isEdit ? client.from("products").update(data).eq("id", editingId) : client.from("products").insert(data); let result = await run(payload); if (result.error && /description|column/i.test(result.error.message)) result = await run({ name: payload.name, price: payload.price, category: payload.category, stock: payload.stock }); if (result.error) setError(`Produk gagal disimpan: ${result.error.message}`); else { const localProduct: RemoteProduct = { id: editingId ?? `new-${Date.now()}`, name: payload.name, price: payload.price, category: payload.category, stock: payload.stock, description: payload.description }; setRemoteProducts((current) => { const next = isEdit ? current.map((item) => sameProductId(item.id, editingId) ? localProduct : item) : [...current, localProduct]; saveProductCache(next); return next; }); setForm(emptyForm); setEditingId(null); } setSaving(false); };
  const deleteProduct = async (id: string | number) => { if (!supabase || !window.confirm("Hapus produk ini?")) return; const { error: deleteError } = await supabase.from("products").delete().eq("id", id); if (deleteError) setError(`Produk gagal dihapus: ${deleteError.message}`); else setRemoteProducts((current) => { const next = current.filter((item) => !sameProductId(item.id, id)); saveProductCache(next); return next; }); };
  const updateOrderStatus = async (sale: Sale, status: OrderStatus) => { saveOrderStatus(sale.order_number, status); setSales((current) => current.map((item) => item.id === sale.id ? { ...item, status } : item)); setSelected((current) => current?.id === sale.id ? { ...current, status } : current); if (supabase && !sale.id.startsWith("local-")) { const { error: statusError } = await supabase.from("orders").update({ status }).eq("id", sale.id); if (statusError) setError(`Status tersimpan di perangkat ini, tetapi belum tersimpan ke database: ${statusError.message}`); } };
  const stockChange = async (product: RemoteProduct, amount: number) => { if (!supabase) return; const next = Math.max(0, product.stock + amount); const { error: updateError } = await supabase.from("products").update({ stock: next }).eq("id", product.id); if (updateError) setError(updateError.message); else setRemoteProducts((current) => { const nextProducts = current.map((item) => sameProductId(item.id, product.id) ? { ...item, stock: next } : item); saveProductCache(nextProducts); return nextProducts; }); };
  const categoryProductCount = (category: string) => productsForAdmin.filter((product) => product.category.trim().toLowerCase() === category.trim().toLowerCase()).length;
  const addCategory = (event: FormEvent) => { event.preventDefault(); const category = newCategory.trim(); if (!category) return; if (editingCategory && categoryProductCount(editingCategory) > 0) { setError("Kategori yang sudah memiliki produk tidak dapat diubah."); return; } if (savedCategories.some((item) => item.toLowerCase() === category.toLowerCase() && item.toLowerCase() !== editingCategory?.toLowerCase())) { setError("Kategori tersebut sudah ada."); return; } const next = editingCategory ? [...new Set(savedCategories.map((item) => item === editingCategory ? category : item))] : [...new Set([...savedCategories, category])]; setSavedCategories(next); saveCategoryCache(next); setForm((current) => ({ ...current, category })); setNewCategory(""); setEditingCategory(null); setError(""); };
  const editCategory = (category: string) => { if (categoryProductCount(category) > 0) { setError("Kategori yang sudah memiliki produk tidak dapat diubah."); return; } setEditingCategory(category); setNewCategory(category); setError(""); };
  const deleteCategory = (category: string) => { if (categoryProductCount(category) > 0) { setError("Kategori yang masih memiliki produk tidak dapat dihapus."); return; } if (!window.confirm(`Hapus kategori ${category}?`)) return; const next = savedCategories.filter((item) => item !== category); setSavedCategories(next); saveCategoryCache(next); if (editingCategory === category) { setEditingCategory(null); setNewCategory(""); } setError(""); };

  const productManager = <section className="admin-panel product-manager"><div className="panel-heading"><div><p className="eyebrow">KELOLA KATALOG</p><h2>{editingId === null ? "Tambah Produk" : "Edit Produk"}</h2></div>{editingId !== null && <button className="panel-link" type="button" onClick={() => { setForm(emptyForm); setEditingId(null); }}>Batal edit</button>}</div><form className="admin-product-form" onSubmit={saveProduct}><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Nama produk" required/><input type="number" min="0" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} placeholder="Harga" required/><select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{categoryNames.map((category) => <option key={category}>{category}</option>)}</select><input type="number" min="0" value={form.stock} onChange={(event) => setForm({ ...form, stock: event.target.value })} placeholder="Stok" required/><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Deskripsi produk" rows={3}/><button className="button dark" type="submit" disabled={saving}>{saving ? "MENYIMPAN..." : editingId === null ? "TAMBAH PRODUK →" : "SIMPAN PERUBAHAN →"}</button></form></section>;
  const productTable = <section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">DATA PRODUK</p><h2>Produk Tersimpan</h2></div></div><div className="admin-product-list">{productsForAdmin.map((product) => <div className="admin-product-row" key={product.id}><div><b>{product.name}</b><small>{product.category} · {formatPrice(product.price)} · terjual {soldFor(product.name)} pcs</small></div><div className="admin-product-actions"><button type="button" onClick={() => stockChange(product, -1)} disabled={product.stock <= 0}>−</button><strong>{product.stock} pcs</strong><button type="button" onClick={() => stockChange(product, 1)}>+</button><button type="button" onClick={() => editProduct(product)}>EDIT</button><button type="button" className="danger" onClick={() => deleteProduct(product.id)}>HAPUS</button></div></div>)}</div></section>;
  const ordersTable = <section className="admin-panel recent-orders"><div className="panel-heading"><div><p className="eyebrow">DATA PESANAN</p><h2>Pesanan</h2></div></div>{loading ? <p className="report-muted">Memuat data...</p> : sales.length === 0 ? <p className="report-muted">Belum ada transaksi.</p> : <div className="recent-order-list">{sales.map((sale) => <div className="admin-order-entry" key={sale.id}><button className="recent-order" onClick={() => setSelected(sale)}><span className="order-mark">▤</span><span><b>{sale.order_number}</b><small>{sale.customer_name} · {sale.whatsapp} · {new Date(sale.created_at).toLocaleDateString("id-ID")}</small><small className="order-address">{sale.address}</small></span><strong>{formatPrice(Number(sale.total))}</strong><i>→</i></button><div className="order-status-control"><span>Status pesanan</span><select value={sale.status ?? "Pesanan diterima"} onChange={(event) => updateOrderStatus(sale, event.target.value as OrderStatus)}>{orderStatuses.map((status) => <option key={status}>{status}</option>)}</select></div></div>)}</div>}</section>;
  const dashboardChart = <section className="admin-panel dashboard-chart-panel"><div className="panel-heading"><div><p className="eyebrow">ANALISIS PENJUALAN</p><h2>Tren penjualan</h2></div><span className="panel-badge">Pendapatan / periode</span></div><div className="chart-filter-row"><label>Periode<select value={chartPeriod} onChange={(event) => setChartPeriod(event.target.value)}><option value="7-hari">7 hari terakhir</option><option value="30-hari">30 hari terakhir</option><option value="3-bulan">3 bulan terakhir</option><option value="tahun-ini">Tahun ini</option><option value="semua">Semua data</option></select></label><label>Tanggal mulai<input type="date" value={chartFrom} onChange={(event) => setChartFrom(event.target.value)} /></label><label>Tanggal akhir<input type="date" value={chartTo} onChange={(event) => setChartTo(event.target.value)} /></label><button type="button" onClick={() => { setChartPeriod("7-hari"); setChartFrom(""); setChartTo(""); }}>Reset</button></div><div className="dashboard-chart-summary"><b>{formatPrice(salesTrend.days.reduce((sum, day) => sum + day.revenue, 0))}</b><span>Total pada periode grafik</span></div><div className="dashboard-chart-wrap"><div className="dashboard-chart-y"><span>{formatPrice(salesTrend.maxRevenue)}</span><span>{formatPrice(Math.round(salesTrend.maxRevenue / 2))}</span><span>Rp 0</span></div><svg className="dashboard-chart-svg" viewBox="0 0 678 265" role="img" aria-label="Grafik pendapatan penjualan sesuai filter"><line x1="42" y1="50" x2="678" y2="50"/><line x1="42" y1="132" x2="678" y2="132"/><line x1="42" y1="214" x2="678" y2="214"/><polyline className="dashboard-chart-area" points={`42,214 ${salesTrend.line} 678,214`}/><polyline className="dashboard-chart-line" points={salesTrend.line}/>{salesTrend.points.map((point) => <g key={`${point.label}-${point.date}`}><circle cx={point.x} cy={point.y} r="5"/><text x={point.x} y="246" textAnchor="middle">{point.label}</text><title>{`${point.label}: ${formatPrice(point.revenue)}`}</title></g>)}</svg></div></section>;
  const dashboard = <><section className="admin-stat-grid"><div className="admin-stat-card"><b>{productsForAdmin.length}</b><span>Produk terdaftar</span></div><div className="admin-stat-card"><b>{sales.length}</b><span>Total pesanan</span><small>{units} unit terjual</small></div><div className="admin-stat-card"><b>{customers}</b><span>Akun pembeli</span></div><div className="admin-stat-card"><b>{formatPrice(revenue)}</b><span>Pendapatan</span></div></section>{dashboardChart}{productTable}{ordersTable}</>;
  const categories = [...new Set([...savedCategories, ...productsForAdmin.map((product) => product.category)])].filter(Boolean).map((category) => ({ category, count: productsForAdmin.filter((product) => product.category === category).length }));
  const reportContent = <>
    <section className="admin-panel report-filters no-print">
      <div className="panel-heading"><div><p className="eyebrow">FILTER LAPORAN</p><h2>Pilih data penjualan</h2></div><button className="button dark" type="button" onClick={printReport}>CETAK LAPORAN →</button></div>
      <div className="report-filter-grid">
        <label>Periode<select value={reportPeriod} onChange={(event) => setReportPeriod(event.target.value)}><option value="semua">Semua periode</option><option value="hari-ini">Hari ini</option><option value="7-hari">7 hari terakhir</option><option value="bulan-ini">Bulan ini</option><option value="tahun-ini">Tahun ini</option></select></label>
        <label>Tanggal mulai<input type="date" value={reportFrom} onChange={(event) => setReportFrom(event.target.value)} /></label>
        <label>Tanggal akhir<input type="date" value={reportTo} onChange={(event) => setReportTo(event.target.value)} /></label>
        <label>Kategori<select value={reportCategory} onChange={(event) => setReportCategory(event.target.value)}><option>Semua kategori</option>{categoryNames.map((category) => <option key={category}>{category}</option>)}</select></label>
      </div>
      <button className="report-reset" type="button" onClick={() => { setReportPeriod("semua"); setReportFrom(""); setReportTo(""); setReportCategory("Semua kategori"); }}>Reset filter</button>
    </section>
    <section className={`admin-panel sales-report ${printingReport ? "print-target" : ""}`}>
      <div className="panel-heading report-heading"><div><p className="eyebrow">LAPORAN PENJUALAN</p><h2>Ringkasan penjualan</h2><small>{reportDescription}</small></div><span className="report-count">{reportSales.length} pesanan</span></div>
      <div className="admin-stat-grid report-stats-inline"><div className="admin-stat-card"><b>{formatPrice(reportRevenue)}</b><span>Total pendapatan</span></div><div className="admin-stat-card"><b>{reportSales.length}</b><span>Pesanan masuk</span></div><div className="admin-stat-card"><b>{reportUnits}</b><span>Unit terjual</span></div><div className="admin-stat-card"><b>{reportCustomers}</b><span>Pelanggan</span></div></div>
      {loading ? <p className="report-muted">Memuat data...</p> : reportSales.length === 0 ? <p className="report-muted">Tidak ada transaksi sesuai filter.</p> : <div className="report-order-list">{reportSales.map((sale) => <button className="report-order-row" key={sale.id} onClick={() => setSelected(sale)}><span><b>{sale.order_number}</b><small>{sale.customer_name} · {new Date(sale.created_at).toLocaleDateString("id-ID")}</small></span><strong>{formatPrice(reportCategory === "Semua kategori" ? Number(sale.total) : sale.items.filter((item) => productsForAdmin.find((product) => product.name.trim().toLowerCase() === item.product_name.trim().toLowerCase())?.category === reportCategory).reduce((sum, item) => sum + item.price * item.quantity, 0))}</strong><i>→</i></button>)}</div>}
    </section>
  </>;
  const content = activeTab === "Dashboard" ? dashboard : activeTab === "Produk" ? <>{productManager}{productTable}</> : activeTab === "Kategori" ? <section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">KATALOG</p><h2>{editingCategory ? "Edit Kategori" : "Tambah Kategori"}</h2></div>{editingCategory && <button className="panel-link" type="button" onClick={() => { setEditingCategory(null); setNewCategory(""); }}>Batal edit</button>}</div><form className="category-form" onSubmit={addCategory}><input value={newCategory} onChange={(event) => setNewCategory(event.target.value)} placeholder="Nama kategori baru" required/><button className="button dark" type="submit">{editingCategory ? "SIMPAN PERUBAHAN →" : "TAMBAH KATEGORI →"}</button></form><div className="panel-heading category-heading"><div><p className="eyebrow">DAFTAR KATEGORI</p><h2>Kategori Produk</h2></div></div>{categories.map((item) => <div className="low-stock-row category-row" key={item.category}><span>{item.category}<small>{item.count ? `${item.count} produk menggunakan kategori ini` : "Belum ada produk dalam kategori"}</small></span><div className="category-row-actions"><b>{item.count} produk</b><button type="button" onClick={() => editCategory(item.category)} disabled={item.count > 0} title={item.count > 0 ? "Kategori sudah digunakan produk" : "Edit kategori"}>EDIT</button><button type="button" className="danger" onClick={() => deleteCategory(item.category)} disabled={item.count > 0} title={item.count > 0 ? "Kategori masih digunakan produk" : "Hapus kategori"}>HAPUS</button></div></div>)}</section> : activeTab === "Pesanan" ? ordersTable : reportContent;

  if (!user || user.role !== "admin") return <main className="admin-page"><div className="admin-head"><div><p className="eyebrow">RUMAH RONA · ADMIN</p><h1>Login admin</h1><p>Masuk untuk mengelola toko dan melihat laporan.</p>{authError && <p className="auth-error">{authError}</p>}</div><a className="back-link" href="/">← Kembali ke toko</a></div><AuthModal onClose={() => window.location.href = "/"} onAuthenticated={(authenticatedUser) => authenticatedUser.role === "admin" ? (setUser(authenticatedUser), setAuthError("")) : setAuthError("Akun ini bukan akun admin.")} /></main>;
  return <main className="admin-page admin-dashboard"><header className="admin-topbar"><div className="admin-brand"><span>✦</span><div><b>RUMAH RONA</b><small>Admin workspace</small></div></div><div className="admin-user"><span className="admin-avatar">A</span><span>{user.email}</span><button onClick={() => { signOutDummy(); supabase?.auth.signOut(); }}>Keluar</button></div></header><nav className="admin-nav">{adminTabs.map((tab) => <button type="button" key={tab} className={activeTab === tab ? "active" : ""} onClick={() => { setActiveTab(tab); window.sessionStorage.setItem("rumah-rona-admin-tab", tab); }}><span>{tab}</span></button>)}</nav><section className="admin-welcome"><div><p className="eyebrow">OVERVIEW · RUMAH RONA</p><h1>{activeTab}</h1><p>Kelola katalog, stok, pesanan, dan laporan toko.</p></div><a className="admin-store-link" href="/" onClick={() => window.sessionStorage.setItem("rumah-rona-view-store", "1")}>Lihat toko ↗</a></section>{error && <p className="auth-error admin-notice">{error}</p>}{content}{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><article className="receipt" onClick={(event) => event.stopPropagation()}><button className="close no-print" onClick={() => setSelected(null)}>×</button><div className="receipt-content"><p className="eyebrow">RUMAH RONA</p><h2>Struk penjualan</h2><p className="receipt-number">{selected.order_number} · {new Date(selected.created_at).toLocaleString("id-ID")}</p><div className="receipt-customer"><b>{selected.customer_name}</b><span>{selected.whatsapp}</span><span>{selected.address}</span></div>{selected.items.map((item, index) => <div className="receipt-item" key={`${item.product_name}-${item.size}-${index}`}><span>{item.product_name}<small>{item.size} · × {item.quantity}</small></span><b>{formatPrice(item.price * item.quantity)}</b></div>)}<div className="receipt-total"><span>Total</span><b>{formatPrice(Number(selected.total))}</b></div><p className="receipt-payment">Pembayaran: {selected.payment_method}</p><button className="button dark no-print" onClick={() => window.print()}>CETAK STRUK →</button></div></article></div>}</main>;
}
