"use client";
import { FormEvent, useState } from "react";
import { supabase } from "../lib/supabase";
import { ADMIN_EMAIL, ADMIN_PASSWORD, DummyUser, signInDummy, signUpDummy } from "../lib/dummyAuth";

export default function AuthModal({ onClose, onAuthenticated }: { onClose: () => void; onAuthenticated: (user: DummyUser) => void }) {
  const [mode, setMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const fallback = () => { const user = mode === "login" ? signInDummy(email, password) : signUpDummy(email, password); if (user) { onAuthenticated(user); return true; } return false; };
  const submit = async (event: FormEvent) => { event.preventDefault(); const normalizedEmail = email.trim().toLowerCase(); if (!normalizedEmail.endsWith("@gmail.com")) { setError("Gunakan email Gmail yang berakhiran @gmail.com."); return; } setLoading(true); setError(""); try { if (mode === "login" && normalizedEmail === ADMIN_EMAIL && password === ADMIN_PASSWORD) { onAuthenticated(signInDummy(normalizedEmail, password)!); return; } if (!supabase) throw new Error("offline"); const result = mode === "login" ? await supabase.auth.signInWithPassword({ email: normalizedEmail, password }) : await supabase.auth.signUp({ email: normalizedEmail, password }); if (result.error) { if (/invalid login|failed to fetch|network|fetch|rate limit|too many|email not confirmed/i.test(result.error.message) && fallback()) return; setError(result.error.message.includes("Invalid login") ? "Email atau password salah." : result.error.message); return; } if (mode === "signup") signUpDummy(normalizedEmail, password); if (mode === "signup" && !result.data.session && fallback()) return; if (!result.data.user) { setError("Akun belum siap digunakan. Coba login kembali."); return; } const accountEmail = result.data.user.email ?? normalizedEmail; onAuthenticated({ email: accountEmail, role: accountEmail.toLowerCase() === ADMIN_EMAIL ? "admin" : "customer" }); } catch { if (!fallback()) setError(mode === "login" ? "Email atau password salah." : "Pendaftaran gagal. Periksa email dan password."); } finally { setLoading(false); } };
  return <div className="modal-backdrop" onClick={onClose}><div className="auth-modal" onClick={(event) => event.stopPropagation()}><button className="close" onClick={onClose}>×</button><p className="eyebrow">RUMAH RONA</p><h2>{mode === "login" ? "Selamat datang kembali" : "Buat akun baru"}</h2><p className="auth-copy">{mode === "login" ? "Masuk dengan akunmu untuk melanjutkan belanja." : "Daftar sekali, lalu akses akunmu dari perangkat mana pun."}</p><form onSubmit={submit}><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email" required /><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password (min. 6 karakter)" minLength={6} required />{error && <p className="auth-error">{error}</p>}<button className="button dark auth-submit" disabled={loading}>{loading ? "MEMPROSES..." : mode === "login" ? "MASUK →" : "DAFTAR →"}</button></form><button className="auth-switch" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); }}>{mode === "login" ? "Belum punya akun? Daftar" : "Sudah punya akun? Masuk"}</button></div></div>;
}
