"use client";
import { useEffect, useMemo, useState } from "react";
import ProductCard from "./ProductCard";
import { Product, products as defaultProducts } from "./types";
import { supabase } from "../lib/supabase";

export default function Catalog({ onAdd }: { onAdd: (product: Product, size: string) => void }) {
  const [category, setCategory] = useState("Semua"); const [query, setQuery] = useState(""); const [products, setProducts] = useState(defaultProducts);
  useEffect(() => { if (!supabase) return; Promise.all([supabase.from("products").select("id, name, price, category, stock, description"), supabase.from("order_items").select("product_name, quantity")]).then(([productResult, itemResult]) => { const sold = new Map<string, number>(); (itemResult.data ?? []).forEach((item) => { const key = String(item.product_name).trim().toLowerCase(); sold.set(key, (sold.get(key) ?? 0) + Number(item.quantity || 0)); }); const remote = productResult.data ?? []; const mapped = defaultProducts.map((product) => { const item = remote.find((row) => String(row.name).trim().toLowerCase() === product.name.trim().toLowerCase()); const remoteStock = Number(item?.stock); const calculatedStock = Math.max(0, (product.stock ?? 10) - (sold.get(product.name.trim().toLowerCase()) ?? 0)); return item ? { ...product, price: Number(item.price ?? product.price), category: item.category || product.category, description: item.description || product.description, stock: Number.isFinite(remoteStock) ? Math.min(remoteStock, calculatedStock) : calculatedStock } : { ...product, stock: calculatedStock }; }); const extra = remote.filter((row) => !defaultProducts.some((product) => product.name.trim().toLowerCase() === String(row.name).trim().toLowerCase())).map((row, index) => ({ id: 10000 + index, name: row.name, price: Number(row.price ?? 0), category: row.category || "Atasan", image: "linen", color: "#d6b48a", sizes: ["S", "M", "L", "XL"], stock: Math.max(0, Number(row.stock ?? 0)), description: row.description || "Produk handmade Rumah Rona." })); setProducts([...mapped, ...extra]); }); }, []);
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return products.filter((product) => (category === "Semua" || product.category === category) && (!term || `${product.name} ${product.category}`.toLowerCase().includes(term))); }, [category, query, products]);
  return <section className="collection" id="koleksi"><div className="section-heading"><div><p className="eyebrow">PILIHAN UNTUKMU</p><h2>Koleksi terbaru</h2></div><a href="#koleksi">Lihat semua <span>→</span></a></div><div className="catalog-tools"><div className="filter-row">{["Semua", "Atasan", "Bawahan", "Outer", "Dress"].map((item) => <button className={category === item ? "active" : ""} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div><label className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari produk..." aria-label="Cari produk" />{query && <button type="button" onClick={() => setQuery("")} aria-label="Hapus pencarian">×</button>}</label></div>{filtered.length ? <div className="product-grid">{filtered.map((product) => <ProductCard product={product} onAdd={onAdd} key={product.id} />)}</div> : <div className="no-results">Produk yang kamu cari belum tersedia.</div>}</section>;
}
